language: node_js
node_js:
    - "8.0"
script:
    - echo "Deploying"
    - npm run lint
    - npm test
cache:
    - node_modules
install:
    - npm install -g firebase-tools
    - npm install
    - npm run build
after_success:
    - firebase deploy --token $FIREBASE_TOKEN
    - npm run coverage
deploy:
  skip_cleanup: true
  provider: pages
  local_dir: build
  on:
    branch: master
